### ISSUE TITLE
weblate i18n request

### ISSUE THREAD

**Issue by NeKoOuO** [null2264/yokai#268]
### Describe your suggested feature

Need this for translation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of Yōkai have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I have updated the app to version **[1.8.5.12](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by infyProductions** [comment]
The way that I updated the translation is editing the corresponding `strings.xml` and `plurals.xml` manually via [tree/master/i18n/src/commonMain/moko-resources](https://github.com/null2264/yokai/tree/master/i18n/src/commonMain/moko-resources) and update the strings manually using the built-in text editor one window and the Weblate page (of J2K or Mihon) on the other window.

This might be helpful since there's a lot of changes to the base strings that either doesn't exist or isn't being used.

**Comment by null2264** [comment]
Here you go: https://hosted.weblate.org/projects/yokai/. It's still in trial so I'm not entirely sure if it will stay or not (it probably will if my Libre hosting is approved).
